version: '3.8'

services:
  app:
    build: .
    container_name: cloudtalk-java
    depends_on:
      - postgres
      - redis
    environment:
       - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - cloudtalk-network

  postgres:
    image: postgres:15
    container_name: cloudtalk-db
    environment:
      POSTGRES_DB: cloudtalkdb
      POSTGRES_USER: cloudtalk
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - cloudtalk-network

  redis:
    image: redis:latest
    container_name: cloudtalk-redis
    ports:
      - "6379:6379"
    networks:
      - cloudtalk-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 5s  

networks:
  cloudtalk-network:
    driver: bridge