version: '3.8'

services:
  app:
    build: .
    container_name: cloudtalk-java
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
       - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - cloudtalk-network

  postgres:
    image: postgres:15
    container_name: cloudtalk-db
    environment:
      POSTGRES_DB: cloudtalkdb
      POSTGRES_USER: cloudtalk
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - cloudtalk-network

  redis:
    image: redis:latest
    container_name: cloudtalk-redis
    ports:
      - "6379:6379"
    networks:
      - cloudtalk-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 5s  
      
  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      container_name: cloudtalk-zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
      networks:
        - cloudtalk-network  

  kafka:
     image: confluentinc/cp-kafka:latest
     container_name: cloudtalk-kafka
     depends_on:
       - zookeeper
     ports:
       - "9092:9092"
     networks:
       - cloudtalk-network  
     environment:
       KAFKA_BROKER_ID: 1
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1   

networks:
  cloudtalk-network:
    driver: bridge